name: build
on: push
jobs:
  build_linux:
    name: build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install pkgs
        run: mkdir deps && sudo ./scripts/install_pkgs_linux.sh
      - name: install deps
        run: ./scripts/install_deps_linux.sh
      - name: build
        run: ./scripts/build_linux.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mac-archive
          path: build/obs-virtualbg-*.zip
